services:
  backend:
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static

  frontend:
    command: bun run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
